apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  selector:
    app: prometheus-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
