apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    io.kompose.service: influxdb
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/node-monitor-net: "true"
        io.kompose.service: influxdb
    spec:
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
            - clone
            - --branch
            - monitoring-stack
            - --
            - https://github.com/DICoE-CGI/indy-node-monitor.git
            - /monitoring-stack
          volumeMounts:
            - mountPath: /monitoring-stack
              name: monitoring-stack-repo
      containers:
        - command: ["/bin/bash", "-c", "--"]
          args:
            - echo "PWD" $(pwd);
              echo "User:" $(whoami);
              cp -r /monitoring-stack-repo/influxdb/config/. /etc/influxdb/;
              /entrypoint.sh influxd;
          image: " "
          name: influxdb
          ports:
            - containerPort: 8086
            - containerPort: 8082
            - containerPort: 8089
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-data
            - mountPath: /monitoring-stack-repo
              name: monitoring-stack-repo
            # - mountPath: /etc/influxdb/
            #   name: influxdb-claim1
      restartPolicy: Always
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
        - name: monitoring-stack-repo
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - influxdb
        from:
          kind: ImageStreamTag
          name: influxdb:1.8
      type: ImageChange
# status:
#   availableReplicas: 0
#   latestVersion: 0
#   observedGeneration: 0
#   replicas: 0
#   unavailableReplicas: 0
#   updatedReplicas: 0
