apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  selector:
    app: monitoring-grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
