apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    io.kompose.service: telegraf
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/node-monitor-net: "true"
        io.kompose.service: telegraf
    spec:
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
            - clone
            - --branch
            - monitoring-stack
            - --
            - https://github.com/DICoE-CGI/indy-node-monitor.git
            - /monitoring-stack
          volumeMounts:
            - mountPath: /monitoring-stack
              name: monitoring-stack-repo
      containers:
        - command: ["/bin/bash", "-c", "--"]
          args:
            - echo "PWD" $(pwd);
              echo "User:" $(whoami);
              cat /entrypoint.sh;
              /entrypoint.sh telegraf --config /monitoring-stack-repo/telegraf/telegraf.conf;
          env:
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: HOSTNAME
                  name: telegraf-env-telegraf
            - name: SBN_SEED
              valueFrom:
                configMapKeyRef:
                  key: SBN_SEED
                  name: telegraf-env-telegraf
            - name: SMN_SEED
              valueFrom:
                configMapKeyRef:
                  key: SMN_SEED
                  name: telegraf-env-telegraf
            - name: SSN_SEED
              valueFrom:
                configMapKeyRef:
                  key: SSN_SEED
                  name: telegraf-env-telegraf
          image: " "
          name: telegraf
          ports:
            - containerPort: 9273
          resources: {}
          volumeMounts:
            - mountPath: /monitoring-stack-repo
              name: monitoring-stack-repo
            # - mountPath: /etc/telegraf/
            #   name: telegraf-claim0
      restartPolicy: Always
      volumes:
        - name: monitoring-stack-repo
        # - name: telegraf-claim0
        #   persistentVolumeClaim:
        #     claimName: telegraf-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - telegraf
        from:
          kind: ImageStreamTag
          name: telegraf:latest
      type: ImageChange
# status:
#   availableReplicas: 0
#   latestVersion: 0
#   observedGeneration: 0
#   replicas: 0
#   unavailableReplicas: 0
#   updatedReplicas: 0
