apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    io.kompose.service: alertmanager
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/node-monitor-net: "true"
        io.kompose.service: alertmanager
    spec:
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
            - clone
            - --branch
            - monitoring-stack
            - --
            - https://github.com/DICoE-CGI/indy-node-monitor.git
            - /monitoring-stack
          volumeMounts:
            - mountPath: /monitoring-stack
              name: monitoring-stack-repo
      containers:
        - args:
            - --config.file=/monitoring-stack-repo/alertmanager/config.yml
            - --storage.path=/alertmanager
          image: " "
          name: alertmanager
          ports:
            - containerPort: 9093
          resources: {}
          volumeMounts:
            - mountPath: /monitoring-stack-repo
              name: monitoring-stack-repo
      restartPolicy: Always
      volumes:
        - name: monitoring-stack-repo
          # persistentVolumeClaim:
          #   claimName: alertmanager-claim0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - alertmanager
        from:
          kind: ImageStreamTag
          name: alertmanager:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
