apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    io.kompose.service: prometheus
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/node-monitor-net: "true"
        io.kompose.service: prometheus
    spec:
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
            - clone
            - --branch
            - monitoring-stack
            - --
            - https://github.com/ConnorBarnes88/indy-node-monitor.git
            - /monitoring-stack
          volumeMounts:
            - mountPath: /monitoring-stack
              name: monitoring-stack-repo
      containers:
        # - command: ["/bin/sh", "-c", "--"]
        #   args:
        #     - echo "PWD" $(pwd);
        #       echo "User:" $(whoami);
        #       cp -r /monitoring-stack-repo/prometheus/. /etc/prometheus;
        #       /bin/prometheus --config.file=/etc/prometheus/prometheus.yml\;
        #       --storage.tsdb.path=/prometheus\;
        #       --web.console.libraries=/usr/share/prometheus/console_libraries\;
        #       --web.console.templates=/usr/share/prometheus/consoles;
        - args:
            - --config.file=/monitoring-stack-repo/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/usr/share/prometheus/console_libraries
            - --web.console.templates=/usr/share/prometheus/consoles
          image: " "
          name: prometheus
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /monitoring-stack-repo
              name: monitoring-stack-repo
            # - mountPath: /etc/prometheus/
            #   name: prometheus-claim0
            - mountPath: /prometheus
              name: prometheus-data
      restartPolicy: Always
      volumes:
        # - name: prometheus-claim0
        #   persistentVolumeClaim:
        #     claimName: prometheus-claim0
        - name: monitoring-stack-repo
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - prometheus
        from:
          kind: ImageStreamTag
          name: prometheus:latest
      type: ImageChange
# status:
#   availableReplicas: 0
#   latestVersion: 0
#   observedGeneration: 0
#   replicas: 0
#   unavailableReplicas: 0
#   updatedReplicas: 0
